In [ ]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/SEM4/Research Method/RM Kel 19 Experiment/data-final.csv", sep='\t')
# dataset = pd.read_csv("/content/drive/MyDrive/RESEARCH METHOD 19/XGBoost/RM Kel 19 Experiment/data-final.csv", sep='\t')
print(dataset.shape)
dataset.head()

(1015341, 110)


EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  \
0   4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   
1   3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   
2   2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   
3   2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   
4   3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   

              dateload  screenw  screenh  introelapse  testelapse  endelapse  \
0  2016-03-03 02:01:01    768.0   1024.0          9.0       234.0          6   
1  2016-03-03 02:01:20   1360.0    768.0         12.0       179.0         11   
2  2016-03-03 02:01:56   1366.0    768.0          3.0       186.0          7   
3  2016-03-03 02:02:02   1920.0   1200.0        186.0       219.0          7   
4  2016-03-03 02:02:57   1366.0    768.0          8.0       315.0         17   

   IPC  country  lat_appx_lots_of_err  long_appx_lots_of_err  
0    1       GB               51.5448                 0.1991  
1    1       MY                3.1698                101.706  
2    1       GB               54.9119                -1.3833  
3    1       GB                 51.75                  -1.25  
4    2       KE                   1.0                   38.0  

[5 rows x 110 columns]

In [ ]:
data = dataset.drop(list(dataset)[50:], axis=1)

print(data.shape)
data.head()

(1015341, 50)


EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  OPN1  \
0   4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   5.0   
1   3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   1.0   
2   2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   5.0   
3   2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   4.0   
4   3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   5.0   

   OPN2  OPN3  OPN4  OPN5  OPN6  OPN7  OPN8  OPN9  OPN10  
0   1.0   4.0   1.0   4.0   1.0   5.0   3.0   4.0    5.0  
1   2.0   4.0   2.0   3.0   1.0   4.0   2.0   5.0    3.0  
2   1.0   2.0   1.0   4.0   2.0   5.0   3.0   4.0    4.0  
3   2.0   5.0   2.0   3.0   1.0   4.0   4.0   3.0    3.0  
4   1.0   5.0   1.0   5.0   1.0   5.0   3.0   5.0    5.0  

[5 rows x 50 columns]

In [ ]:
for i in data.columns:
  data = data[(data[i].notna()) & (data[i] != 0)]

print(data.shape)

(874434, 50)


In [ ]:
data['EST9'].value_counts()

4.0    247851
2.0    199050
3.0    182001
5.0    133152
1.0    112380
Name: EST9, dtype: int64

In [ ]:
x = data.drop(columns=['EST9'])
y = data['EST9']

In [ ]:
print(data.shape)

(874434, 50)


### Split train set - test set

In [ ]:
sel_x = data[['EST6', 'EST8', 'EST7', 'AGR3', 'EST1', 'EST5', 'EST10','EST3', 'AGR7', 'AGR6', 'EST2', 'CSN9', 'AGR4', 'AGR5']]

print(sel_x.shape)

sel_x.head()

(874434, 14)


EST6  EST8  EST7  AGR3  EST1  EST5  EST10  EST3  AGR7  AGR6  EST2  CSN9  \
0   2.0   2.0   2.0   2.0   1.0   2.0    2.0   4.0   2.0   3.0   4.0   4.0   
1   1.0   1.0   2.0   1.0   2.0   3.0    1.0   4.0   3.0   5.0   3.0   5.0   
2   2.0   2.0   2.0   1.0   4.0   2.0    3.0   4.0   1.0   4.0   4.0   4.0   
3   2.0   2.0   2.0   3.0   3.0   3.0    3.0   3.0   2.0   4.0   3.0   1.0   
4   1.0   1.0   1.0   1.0   1.0   1.0    2.0   5.0   1.0   3.0   5.0   5.0   

   AGR4  AGR5  
0   4.0   2.0  
1   5.0   1.0  
2   4.0   2.0  
3   4.0   2.0  
4   5.0   1.0

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(sel_x, y, test_size = 0.2)

In [ ]:
y_train_1 = y_train - 1
y_test_1 = y_test - 1

# Training XGBoost

In [ ]:
import xgboost as xgb

In [ ]:
xgb_clf = xgb.XGBClassifier(objective='multi:softmax',
                            num_class=5,
                            missing=0,
                            early_stopping_rounds=10,
                            eval_metric=['merror','mlogloss'],
                            seed=42)

In [ ]:
xgb_clf.fit(x_train, y_train_1, verbose=0, eval_set=[(x_train, y_train_1), (x_test, y_test_1)])

In [ ]:
y_pred = xgb_clf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\n-------------------- Key Metrics --------------------')
print('\nAccuracy: {:.2f}'.format(accuracy_score(y_test_1, y_pred)))
print('Balanced Accuracy: {:.4f}\n'.format(balanced_accuracy_score(y_test_1, y_pred)))

print('Micro Precision: {:.2f}'.format(precision_score(y_test_1, y_pred, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_test_1, y_pred, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test_1, y_pred, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_test_1, y_pred, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_test_1, y_pred, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test_1, y_pred, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_test_1, y_pred, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_test_1, y_pred, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_test_1, y_pred, average='weighted')))

# print('\n--------------- Classification Report ---------------\n')
# print(classification_report(y_test_1, y_pred))
# print('---------------------- XGBoost ----------------------')


------------------ Confusion Matrix -----------------

[[    0     0     0     0     0     0]
 [13021  6148  1301  1337   646     0]
 [ 4861 21986  5670  6759   722     0]
 [ 2032  8998 12131 11224  1629     0]
 [ 1354  6373  6301 30576  5135     0]
 [  694   729  1268  8762 15230     0]]

-------------------- Key Metrics --------------------

Accuracy: 0.53
Balanced Accuracy: 0.53

Micro Precision: 0.53
Micro Recall: 0.53
Micro F1-score: 0.53

Macro Precision: 0.54
Macro Recall: 0.53
Macro F1-score: 0.53

Weighted Precision: 0.53
Weighted Recall: 0.53
Weighted F1-score: 0.53


In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
y_pred_ovr = xgb_clf.predict_proba(x_test)

In [ ]:
roc_auc_score(y_test_1, y_pred_ovr, multi_class='ovr')

0.8282356411386596