In [ ]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/SEM4/Research Method/RM Kel 19 Experiment/data-final.csv", sep='\t')
# dataset = pd.read_csv("/content/drive/MyDrive/RESEARCH METHOD 19/XGBoost/RM Kel 19 Experiment/data-final.csv", sep='\t')
print(dataset.shape)
dataset.head()

(1015341, 110)


EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  \
0   4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   
1   3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   
2   2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   
3   2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   
4   3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   

              dateload  screenw  screenh  introelapse  testelapse  endelapse  \
0  2016-03-03 02:01:01    768.0   1024.0          9.0       234.0          6   
1  2016-03-03 02:01:20   1360.0    768.0         12.0       179.0         11   
2  2016-03-03 02:01:56   1366.0    768.0          3.0       186.0          7   
3  2016-03-03 02:02:02   1920.0   1200.0        186.0       219.0          7   
4  2016-03-03 02:02:57   1366.0    768.0          8.0       315.0         17   

   IPC  country  lat_appx_lots_of_err  long_appx_lots_of_err  
0    1       GB               51.5448                 0.1991  
1    1       MY                3.1698                101.706  
2    1       GB               54.9119                -1.3833  
3    1       GB                 51.75                  -1.25  
4    2       KE                   1.0                   38.0  

[5 rows x 110 columns]

In [ ]:
data = dataset.drop(list(dataset)[50:], axis=1)

print(data.shape)
data.head()

(1015341, 50)


EXT1  EXT2  EXT3  EXT4  EXT5  EXT6  EXT7  EXT8  EXT9  EXT10  ...  OPN1  \
0   4.0   1.0   5.0   2.0   5.0   1.0   5.0   2.0   4.0    1.0  ...   5.0   
1   3.0   5.0   3.0   4.0   3.0   3.0   2.0   5.0   1.0    5.0  ...   1.0   
2   2.0   3.0   4.0   4.0   3.0   2.0   1.0   3.0   2.0    5.0  ...   5.0   
3   2.0   2.0   2.0   3.0   4.0   2.0   2.0   4.0   1.0    4.0  ...   4.0   
4   3.0   3.0   3.0   3.0   5.0   3.0   3.0   5.0   3.0    4.0  ...   5.0   

   OPN2  OPN3  OPN4  OPN5  OPN6  OPN7  OPN8  OPN9  OPN10  
0   1.0   4.0   1.0   4.0   1.0   5.0   3.0   4.0    5.0  
1   2.0   4.0   2.0   3.0   1.0   4.0   2.0   5.0    3.0  
2   1.0   2.0   1.0   4.0   2.0   5.0   3.0   4.0    4.0  
3   2.0   5.0   2.0   3.0   1.0   4.0   4.0   3.0    3.0  
4   1.0   5.0   1.0   5.0   1.0   5.0   3.0   5.0    5.0  

[5 rows x 50 columns]

In [ ]:
for i in data.columns:
  data = data[(data[i].notna()) & (data[i] != 0)]

print(data.shape)

(874434, 50)


In [ ]:
data['EST9'].value_counts()

4.0    247851
2.0    199050
3.0    182001
5.0    133152
1.0    112380
Name: EST9, dtype: int64

In [ ]:
x = data.drop(columns=['EST9'])
y = data['EST9']

In [ ]:
print(data.shape)

(874434, 50)


### Random oversampling

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
oversampler = RandomOverSampler(random_state=42)

In [ ]:
X_resampled, y_resampled = oversampler.fit_resample(x, y)

### Split train set - test set

In [ ]:
sel_x = data[['EST6', 'EST8', 'EST7', 'AGR3', 'EST1', 'EST5', 'EST10','EST3', 'AGR7', 'AGR6', 'EST2', 'CSN9', 'AGR4', 'AGR5']]

print(sel_x.shape)

sel_x.head()

(874434, 14)


EST6  EST8  EST7  AGR3  EST1  EST5  EST10  EST3  AGR7  AGR6  EST2  CSN9  \
0   2.0   2.0   2.0   2.0   1.0   2.0    2.0   4.0   2.0   3.0   4.0   4.0   
1   1.0   1.0   2.0   1.0   2.0   3.0    1.0   4.0   3.0   5.0   3.0   5.0   
2   2.0   2.0   2.0   1.0   4.0   2.0    3.0   4.0   1.0   4.0   4.0   4.0   
3   2.0   2.0   2.0   3.0   3.0   3.0    3.0   3.0   2.0   4.0   3.0   1.0   
4   1.0   1.0   1.0   1.0   1.0   1.0    2.0   5.0   1.0   3.0   5.0   5.0   

   AGR4  AGR5  
0   4.0   2.0  
1   5.0   1.0  
2   4.0   2.0  
3   4.0   2.0  
4   5.0   1.0

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size = 0.2)

In [ ]:
y_train_1 = y_train - 1
y_test_1 = y_test - 1

# Training XGBoost

In [ ]:
import xgboost as xgb

In [ ]:
xgb_clf = xgb.XGBClassifier(objective='multi:softmax',
                            num_class=5,
                            missing=0,
                            early_stopping_rounds=10,
                            eval_metric=['merror','mlogloss'],
                            seed=42)

In [ ]:
xgb_clf.fit(x_train, y_train_1, verbose=0, eval_set=[(x_train, y_train_1), (x_test, y_test_1)])

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=10,
              enable_categorical=False, eval_metric=['merror', 'mlogloss'],
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=0,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_class=5, num_parallel_tree=None, objective='multi:softmax', ...)

In [ ]:
y_pred = xgb_clf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import balanced_accuracy_score, accuracy_score, precision_score, recall_score, f1_score

In [ ]:
print('\n------------------ Confusion Matrix -----------------\n')
print(confusion_matrix(y_test, y_pred))

print('\n-------------------- Key Metrics --------------------')
print('\nAccuracy: {:.4f}'.format(accuracy_score(y_test_1, y_pred)))
print('Balanced Accuracy: {:.4f}\n'.format(balanced_accuracy_score(y_test_1, y_pred)))

print('Micro Precision: {:.4f}'.format(precision_score(y_test_1, y_pred, average='micro')))
print('Micro Recall: {:.4f}'.format(recall_score(y_test_1, y_pred, average='micro')))
print('Micro F1-score: {:.4f}\n'.format(f1_score(y_test_1, y_pred, average='micro')))

print('Macro Precision: {:.4f}'.format(precision_score(y_test_1, y_pred, average='macro')))
print('Macro Recall: {:.4f}'.format(recall_score(y_test_1, y_pred, average='macro')))
print('Macro F1-score: {:.4f}\n'.format(f1_score(y_test_1, y_pred, average='macro')))

print('Weighted Precision: {:.4f}'.format(precision_score(y_test_1, y_pred, average='weighted')))
print('Weighted Recall: {:.4f}'.format(recall_score(y_test_1, y_pred, average='weighted')))
print('Weighted F1-score: {:.4f}'.format(f1_score(y_test_1, y_pred, average='weighted')))

# print('\n--------------- Classification Report ---------------\n')
# print(classification_report(y_test_1, y_pred))
# print('---------------------- XGBoost ----------------------')


------------------ Confusion Matrix -----------------

[[    0     0     0     0     0     0]
 [35462  8274  2931  1464  1748     0]
 [10099 23718  8632  5331  1597     0]
 [ 4626 10612 20421 10003  3664     0]
 [ 2474  5952  9102 22873  9010     0]
 [ 1791  1177  2931  9012 34947     0]]

-------------------- Key Metrics --------------------

Accuracy: 0.5545
Balanced Accuracy: 0.5538

Micro Precision: 0.5545
Micro Recall: 0.5545
Micro F1-score: 0.5545

Macro Precision: 0.5495
Macro Recall: 0.5538
Macro F1-score: 0.5511

Weighted Precision: 0.5500
Weighted Recall: 0.5545
Weighted F1-score: 0.5517


In [ ]:
xgb_clf.feature_importances_

array([0.00385917, 0.00522887, 0.00573889, 0.00431787, 0.00411054,
       0.00634407, 0.00449439, 0.00547264, 0.00486677, 0.00862476,
       0.04943155, 0.01244425, 0.01803631, 0.00442049, 0.03846254,
       0.387885  , 0.0713486 , 0.09360746, 0.01641857, 0.0054714 ,
       0.00842059, 0.05175691, 0.01152877, 0.01167952, 0.01352776,
       0.01416595, 0.00822651, 0.00775809, 0.00908625, 0.00414661,
       0.00416135, 0.00388421, 0.00489464, 0.00743422, 0.00459537,
       0.01033675, 0.00438054, 0.01247781, 0.0051158 , 0.00404521,
       0.00484172, 0.00387556, 0.00669579, 0.00431354, 0.00425235,
       0.00518304, 0.0070151 , 0.0077128 , 0.00390313], dtype=float32)

In [ ]:
importance_scores = xgb_clf.feature_importances_

feature_importance = dict(zip(x.columns, importance_scores))

sorted_features = sorted(feature_importance.items(), key=lambda x: x[1], reverse=True)

sorted_features

[('EST6', 0.387885),
 ('EST8', 0.09360746),
 ('EST7', 0.0713486),
 ('AGR3', 0.05175691),
 ('EST1', 0.04943155),
 ('EST5', 0.038462542),
 ('EST3', 0.018036306),
 ('EST10', 0.016418567),
 ('AGR7', 0.014165952),
 ('AGR6', 0.013527763),
 ('CSN9', 0.012477813),
 ('EST2', 0.012444246),
 ('AGR5', 0.011679517),
 ('AGR4', 0.01152877),
 ('CSN7', 0.0103367455),
 ('AGR10', 0.009086247),
 ('EXT10', 0.008624763),
 ('AGR2', 0.00842059),
 ('AGR8', 0.008226511),
 ('AGR9', 0.007758093),
 ('OPN9', 0.0077128024),
 ('CSN5', 0.0074342187),
 ('OPN8', 0.0070151007),
 ('OPN4', 0.006695788),
 ('EXT6', 0.0063440683),
 ('EXT3', 0.0057388945),
 ('EXT8', 0.005472644),
 ('AGR1', 0.0054714005),
 ('EXT2', 0.0052288743),
 ('OPN7', 0.0051830397),
 ('CSN10', 0.0051157996),
 ('CSN4', 0.0048946356),
 ('EXT9', 0.004866774),
 ('OPN2', 0.004841722),
 ('CSN6', 0.004595367),
 ('EXT7', 0.0044943877),
 ('EST4', 0.0044204923),
 ('CSN8', 0.0043805414),
 ('EXT4', 0.0043178736),
 ('OPN5', 0.004313537),
 ('OPN6', 0.0042523528),
 ('CSN

In [ ]:
X_resampledfrom sklearn.metrics import roc_auc_score

In [ ]:
y_pred_ovr = xgb_clf.predict_proba(x_test)

In [ ]:
roc_auc_score(y_test_1, y_pred_ovr, multi_class='ovr')

0.82725005947194